#!/usr/bin/env python
# -*- coding: utf-8 -*-
from email import parser
import re, sys
from main import arg_work

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(arg_work())
